application: style-buzz
version: 3
runtime: python27
api_version: 1
threadsafe: no

# Version 1 (can't remember)
# Version 2 Flask shell. Hardwired content
# Version 3 With Database, gets data from twitter query

handlers:
- url: .*
  script: main.py

- url: /css
  static_dir: css

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /cron
  script: cron.py
  login: admin

libraries:
- name: numpy
  version: "1.6.1"
